### ISSUE TITLE
Non-interactive 'serve' chart in Jupyter Lab

### ISSUE THREAD

**Issue by James-G-Hill** [KoichiYasuoka/deplacy#1]
Is there anyway to view the chart created by 'serve' function in Jupyter Lab without it being interactive

So just an image or SVG created as at this link:
https://raw.githubusercontent.com/KoichiYasuoka/deplacy/master/serve.png

It seems like it is possible to do this with the `UD-Kanbun` package, but not if you use 'udkanban.spacy' to load, because there is no way to switch from the spacy 'Doc' object type to the `UD-Kanbun` 'UDPipeEntry' or 'UDKanbunEntry' object types.

However, in `deplacy` it's possible to create the dependency chart (as shown in the png above) but only with the 'conllu' print out immediately above it, and with an interactive element where it's possible to modify the dependencies shown by dragging a red arrow between the nodes.

What I am trying to achieve is to simply display the visual alone in a non-interactive way within Jupyter Lab; as it is displayed here after clicking 解析:
http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/kyodokenkyu/2018-12-01.html

**Comment by KoichiYasuoka** [comment]
I'm not so familiar with "Jupyter Lab", but I've just tried in Google Colaboratory:

```
!pip install deplacy
import spacy
nlp=spacy.load("en")
doc=nlp("I saw a horse yesterday which had no name")
import deplacy
deplacy.deplacy.EDITOR_URL=deplacy.deplacy.EDITOR_URL.replace("editor.html","viewer.svg")
deplacy.serve(doc,port=None)
```

However, it seems very dirty hack...

**Comment by James-G-Hill** [comment]
Okay, I will give it a try this weekend.

**Comment by James-G-Hill** [comment]
That's great, I can confirm that your solution works with Jupyter Lab.
A follow up question: is there any way to control the settings of the output chart in more detail?  for example, colors of background, text, arrows?

Great work by the way.

**Comment by KoichiYasuoka** [comment]
> A follow up question: is there any way to control the settings of the output chart in more detail? for example, colors of background, text, arrows?

Well, changing colors seems very hard task since they are written in JavaScript [conllusvgview.js](https://github.com/KoichiYasuoka/deplacy/blob/master/deplacy/conllusvgview.js)

**Comment by James-G-Hill** [comment]
Yeah, thanks, I realised that after some further investigation; probably the simplest I can do is create a custom .svg to link to instead of the one you created on github.io.  I only need to change the background color for my purpose and can add that into the svg header.

Thanks for your help.
