### ISSUE TITLE
Clarifying the interface of input data

### ISSUE THREAD

**Issue by Astromis** [KoichiYasuoka/deplacy#3]
Hello.

I recently found your project and was very excited about that because it is one instrument that allows to draw UD tree in Python. I want to incorporate your lib into mine. The issue is that you are using some pretty common way to represent the input from various sources, but unfortunately, I can't fully understand how exactly I have to form my data.

Could you provide a description of that, please? Maybe with some common data class that should have certain fields.

**Comment by KoichiYasuoka** [comment]
The input of `deplacy` is mainly based on [CoNLL-U Format](https://universaldependencies.org/format.html) as tab-separated 10-column UTF-8 string of python3. Other formats are once converted into CoNLL-U with `deplacy.to_conllu()`

**Comment by Astromis** [comment]
Thank you for a quick answer.

So I can use just a conllu formatted string and that will work, right?

**Comment by Astromis** [comment]
I tested a plain conllu string and that works. Amazing.
Thank you.
