### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by vsraptor** [KoichiYasuoka/deplacy#4]
Does this module supports raw data like the example here 

[raw data](https://spacy.io/usage/visualizers#manual-usage)
```

{
    "words": [
        {"text": "This", "tag": "DT"},
        {"text": "is", "tag": "VBZ"},
        {"text": "a", "tag": "DT"},
        {"text": "sentence", "tag": "NN"}
    ],
    "arcs": [
        {"start": 0, "end": 1, "label": "nsubj", "dir": "left"},
        {"start": 2, "end": 3, "label": "det", "dir": "left"},
        {"start": 1, "end": 3, "label": "attr", "dir": "right"}
    ]
}
```

**Comment by KoichiYasuoka** [comment]
Hi @vsraptor the input of `deplacy` is mainly based on [CoNLL-U Format](https://universaldependencies.org/format.html) as tab-separated 10-column UTF-8 string of python3. Your raw data seem much different from CoNLL-U.

**Comment by vsraptor** [comment]
I see.. like here 

https://koichiyasuoka.github.io/deplacy/deplacy/editor.html

you are converting spac-doc to conll-u format internally ?
